name: CI


on: [ push ]

jobs:
  build:  
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - name: Docker image build 
        run: |
          docker build ./src -t Latest:1.0.0

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
